spring.jpa.hibernate.ddl-auto: none
spring.liquibase.enabled: true

management:
    endpoints:
        web.exposure.include: health,info
    endpoint.health:
        show-details: always
    endpoint.info.enabled: true
    metrics.export.simple.enabled: true
    health.diskspace.enabled: false
    health.vault.enabled: true # Erreur 473 - performancestandbycode

spring.main.banner-mode: "off"

springfox.documentation.swagger:
    v2.path: /swagger/v2
    v1.path: /swagger/v1

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

spring:
    liquibase:
        change-log: 'classpath:db/changelog/liquibase-changelog.xml'


