spring.jpa.hibernate.ddl-auto: none
spring.liquibase.enabled: true
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

management:
    endpoints:
        web.exposure.include: health,info
    endpoint.health:
        show-details: always
    endpoint.info.enabled: true
    metrics.export.simple.enabled: true
    health.diskspace.enabled: false
    health.vault.enabled: true # Erreur 473 - performancestandbycode

spring.main.banner-mode: "off"

spring.liquibase.change-log: 'classpath:db/changelog/liquibase-changelog.xml'
server.compression.enabled: true

logging.level:
    root: ${LOGGING_LEVEL_ROOT:WARN}
    io.soffa: ${LOGGING_LEVEL_SOFFA:INFO}
    org.springframework: ${LOGGING_LEVEL_SPRING:INFO}
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.datasource.hikari.connectionTimeout: 20000
spring.datasource.hikari.maximumPoolSize: 5

spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
