
name: pipeline-default

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:latest
    steps:
      - uses: actions/checkout@v1
      - name: Build project
        run: |
          gradle check --watch-fs
