
name: pipeline-master

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        container: gradle:6.3-jdk8
        steps:
            - uses: actions/checkout@v1
            - name: Build
              run: |
                  gradle check
            - name: Sonatype:Release
              env:
                  NEXUS_USERNAME: ${{ secrets.MAVEN_PUBLIC_USERNAME }}
                  NEXUS_PASSWORD: ${{ secrets.MAVEN_PUBLIC_PASSWORD }}
                  SIGNING_KEY_ID: ${{ secrets.MAVEN_PUBLIC_SIGNING_KEY_ID }}
                  SIGNING_KEY_PASSWORD: ${{ secrets.MAVEN_PUBLIC_SIGNING_KEY_PASSWORD }}
                  SONATYPE_GPG: ${{ secrets.SONATYPE_GPG_BASE64 }}
              run: |
                  echo $SONATYPE_GPG | base64 -d > $HOME/.sonatype-keys.gpg
                  gradle sign publishToSonatype closeAndReleaseRepository \
                    -Dorg.gradle.internal.publish.checksums.insecure=true \
                    -Psigning.keyId=$SIGNING_KEY_ID \
                    -Psigning.password=$SIGNING_KEY_PASSWORD \
                    -Psigning.secretKeyRingFile=$HOME/.sonatype-keys.gpg \
                    -PsonatypeUsername=$NEXUS_USERNAME \
                    -PsonatypePassword=$NEXUS_PASSWORD
