name: pipeline-master

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    container: gradle:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check
        run: gradle check
      - name: Publish
        run: |
          echo $GITHUB_ACTOR
          echo $GITHUB_TOKEN
          echo $MVN_USERNAME
          echo $MVN_PASSWORD
          gradle publish -PmvnUsername=$MVN_USERNAME -PmvnPassword=$MVN_PASSWORD
#            - name: Sonatype:Release
#              env:
#                  NEXUS_USERNAME: ${{ secrets.MAVEN_PUBLIC_USERNAME }}
#                  NEXUS_PASSWORD: ${{ secrets.MAVEN_PUBLIC_PASSWORD }}
#                  SIGNING_KEY_ID: ${{ secrets.MAVEN_PUBLIC_SIGNING_KEY_ID }}
#                  SIGNING_KEY_PASSWORD: ${{ secrets.MAVEN_PUBLIC_SIGNING_KEY_PASSWORD }}
#                  SONATYPE_GPG: ${{ secrets.SONATYPE_GPG_BASE64 }}
#              run: |
#                  echo $SONATYPE_GPG | base64 -d > $HOME/.sonatype-keys.gpg
#                  gradle sign publishToSonatype closeAndReleaseRepository --watch-fs \
#                    -Dorg.gradle.internal.publish.checksums.insecure=true \
#                    -Psigning.keyId=$SIGNING_KEY_ID \
#                    -Psigning.password=$SIGNING_KEY_PASSWORD \
#                    -Psigning.secretKeyRingFile=$HOME/.sonatype-keys.gpg \
#                    -PsonatypeUsername=$NEXUS_USERNAME \
#                    -PsonatypePassword=$NEXUS_PASSWORD
