
name: pipeline-master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:5.6.2-jdk8
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          gradle build
      - name: Publish package
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_USER: "startupstation"
        run: |
            gradle publish
#      - name: Sonatype:Release
#        env:
#          NEXUS_USERNAME: ${{ secrets.MAVEN_PUBLIC_USERNAME }}
#          NEXUS_PASSWORD: ${{ secrets.MAVEN_PUBLIC_PASSWORD }}
#          SIGNING_KEY_ID: ${{ secrets.MAVEN_PUBLIC_SIGNING_KEY_ID }}
#          SIGNING_KEY_PASSWORD: ${{ secrets.MAVEN_PUBLIC_SIGNING_KEY_PASSWORD }}
#          SONATYPE_GPG: ${{ secrets.SONATYPE_GPG_BASE64 }}
#        run: |
#          echo $SONATYPE_GPG | base64 -d > $HOME/.sonatype-keys.gpg
#          gradle uploadArchives -Prelease=true \
#            -Psigning.keyId=$SIGNING_KEY_ID \
#            -Psigning.password=$SIGNING_KEY_PASSWORD \
#            -Psigning.secretKeyRingFile=$HOME/.sonatype-keys.gpg \
#            -PnexusUsername=$NEXUS_USERNAME \
#            -PnexusPassword=$NEXUS_PASSWORD
#          gradle closeAndReleaseRepository -PnexusUsername=$NEXUS_USERNAME -PnexusPassword=$NEXUS_PASSWORD
